### ISSUE TITLE
Removing RelationshipEntity 

### ISSUE THREAD

**Issue by airbase9018** [graphaware/neo4j-php-ogm#10]
I was trying your library. 

How do you remove the relationship if it exists?
Like the Rating of a user to a movie?

Thanks a lot.

**Comment by ikwattro** [comment]
In order to remove an existing relationship, you will have to load them from the database, a simple example of user ratings to movie would be like : 

```php
$user = $userRepository->findBy("login"=>"me");
$ratings = $user->getRatings();
// Find the rating on the movie "The Matrix"
foreach ($ratings as $rating) {
  if ($rating->getMovie()->getTitle() === "The Matrix") {
    $user->getMovies()->removeElement($rating);
    $rating()->getMovie()->getRatings()->removeElement($rating); // this is currently optional
}

$entityManager->flush();
```

The `removeElement` method is inherited from the `ArrayCollection` class from `Doctrine`, if you are used to Doctrine2 it works pretty much the same.

**Comment by airbase9018** [comment]
Thanks. I've tried this before but not sure if this was the right implementation. :)

Seems that I need to study Doctrine. Or just use neo4j-php-client as it seems this library is not complete yet for production.

Just want to suggest also: Better to add LIMIT/ORDER when retrieving relationships/nodes based on properties.

very good library IMHO. 👍

**Comment by ikwattro** [comment]
Thanks. Actually I integrated the `lazy` annotation in order to not fetch the relationships immediately but only when you access them. This is at then end of the documentation.

Next steps are pagination so you will be happy ;-)

Yes this is not production ready yet, I don't have an ETA for it neither as I work on it primarly during my spare time.

**Comment by ikwattro** [comment]
Fixed by https://github.com/graphaware/neo4j-php-ogm/commit/737cf2a4e07473343960f7b2460aa69ea129951f
