### ISSUE TITLE
Stable version?

### ISSUE THREAD

**Issue by ZaphodBBX** [graphaware/neo4j-php-ogm#51]
Thanks @graphaware !!
Not really an issue but is there a stable version coming up ? 
stability is still at dev?

**Comment by Nyholm** [comment]
I've been using the lastest beta in production for a while. It works and it is really good. I believe there are a few things that should be implemented before tagging a stable release. Those things might break BC. 

So, yes, it is a stable version coming up. I (don't know but I) guess it will be in Mars.

**Comment by ikwattro** [comment]
Yes there will be BC breaks before stable release, the biggest change is removing the `@Lazy` annotation (default will be lazy) and adding the `Fetch` annotation for `non-lazy`.

Otherwise there are things that are not stable in the actual beta (ref the issues). It is a long wanted project though, giving to it what I can when I can.

**Comment by ZaphodBBX** [comment]
Alright, good to know it's production ready!
And 👍 to have lazy loading as default setting 😄
